language: go
sudo: false
go:
  - '1.8.x'
  - '1.9.x'
  - '1.10.x'
go_import_path: github.com/imperfectgo/zap-syslog
cache:
  directories:
    - vendor
install:
  - make dependencies
script:
  - make test
  - make bench
after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false

